kind: ClusterRole
rules:
  - apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
    verbs:
      - '*'
  - apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - 'clusterrolebindings'
      - 'clusterroles'
    verbs:
      - '*'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - 'mutatingwebhookconfigurations'
    verbs:
      - '*'
  - apiGroups:
      - 'extensions.kubesphere.io'
    resources:
      - '*'
    verbs:
      - '*'

---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'