apiVersion: v1
kind: Service
metadata:
  name: mutato-webhook
  labels:
    {{- include "mutato-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "mutato-webhook.selectorLabels" . | nindent 4 }}
